# Generated by Django 4.2.7 on 2025-12-13 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_due', 'Payment Due'), ('payment_confirmed', 'Payment Confirmed'), ('homework_assigned', 'Homework Assigned'), ('homework_reviewed', 'Homework Reviewed'), ('lesson_scheduled', 'Lesson Scheduled'), ('lesson_rescheduled', 'Lesson Rescheduled'), ('lesson_cancelled', 'Lesson Cancelled'), ('attendance_marked', 'Attendance Marked'), ('coins_earned', 'Coins Earned'), ('system_message', 'System Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='Related object ID (payment, homework, etc)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Related object type (payment, homework, etc)', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_enabled', models.BooleanField(default=True, help_text='Receive notifications via Telegram')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Receive notifications via SMS')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive notifications via Email')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Telegram chat ID', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS', max_length=20)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('homework_notifications', models.BooleanField(default=True)),
                ('lesson_notifications', models.BooleanField(default=True)),
                ('attendance_notifications', models.BooleanField(default=True)),
                ('gamification_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
