# Generated by Django 4.2.7 on 2025-12-13 18:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('second_chance', 'Second Chance')], default='assigned', max_length=20)),
                ('description', models.TextField(help_text='Homework description (Turkish)')),
                ('audio_submission', models.FileField(blank=True, help_text="Student's audio submission", null=True, upload_to='homework_submissions/%Y/%m/')),
                ('submission_date', models.DateTimeField(blank=True, help_text='When student submitted', null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Submission attempt number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('similarity_score', models.FloatField(blank=True, help_text='Similarity score (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('transcription', models.TextField(blank=True, help_text='Transcribed text from audio')),
                ('is_similarity_passed', models.BooleanField(blank=True, help_text='Whether passed similarity check', null=True)),
                ('teacher_feedback', models.TextField(blank=True, help_text="Teacher's feedback")),
                ('reviewed_date', models.DateTimeField(blank=True, help_text='When teacher reviewed', null=True)),
                ('deadline', models.DateTimeField(help_text='Homework deadline')),
                ('is_late', models.BooleanField(default=False, help_text='Whether submitted after deadline')),
                ('coins_earned', models.PositiveIntegerField(default=0, help_text='Coins earned for submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='lessons.lesson')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_homeworks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
                'db_table': 'homeworks',
                'ordering': ['-created_at'],
                'unique_together': {('lesson', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Raw transcription from Whisper')),
                ('cleaned_text', models.TextField(help_text='Cleaned and processed transcription')),
                ('confidence_score', models.FloatField(help_text='Whisper confidence score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('language', models.CharField(default='tr', help_text='Detected language', max_length=10)),
                ('processing_time_seconds', models.FloatField(help_text='Time taken to process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='homework.homework')),
            ],
            options={
                'verbose_name': 'Homework Transcript',
                'verbose_name_plural': 'Homework Transcripts',
                'db_table': 'homework_transcripts',
            },
        ),
    ]
