# Generated by Django 4.2.7 on 2025-12-13 18:48

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_threshold', models.FloatField(default=0.5, help_text='Similarity score threshold for homework (0-1)', validators=[core.validators.SimilarityThresholdValidator()])),
                ('audio_processing_enabled', models.BooleanField(default=True, help_text='Enable audio transcription and scoring')),
                ('lesson_completion_coins', models.PositiveIntegerField(default=10, help_text='Coins awarded for lesson completion', validators=[core.validators.CoinAmountValidator()])),
                ('homework_submission_coins', models.PositiveIntegerField(default=5, help_text='Coins awarded for homework submission', validators=[core.validators.CoinAmountValidator()])),
                ('homework_approved_coins', models.PositiveIntegerField(default=10, help_text='Coins awarded when homework is approved', validators=[core.validators.CoinAmountValidator()])),
                ('attendance_bonus_coins', models.PositiveIntegerField(default=2, help_text='Coins awarded for perfect attendance', validators=[core.validators.CoinAmountValidator()])),
                ('leaderboard_bonus_coins', models.PositiveIntegerField(default=50, help_text='Coins awarded for leaderboard first place', validators=[core.validators.CoinAmountValidator()])),
                ('homework_deadline_hours', models.PositiveIntegerField(default=24, help_text='Hours until homework deadline')),
                ('max_homework_attempts', models.PositiveIntegerField(default=3, help_text='Maximum homework submission attempts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('overdue_payment_day', models.PositiveIntegerField(default=5, help_text='Days after due date to mark payment overdue')),
                ('max_audio_file_size_mb', models.PositiveIntegerField(default=50, help_text='Maximum audio file size in MB')),
                ('supported_audio_formats', models.CharField(default='mp3,wav,ogg,m4a', help_text='Comma-separated list of supported audio formats', max_length=255)),
                ('default_lesson_duration_minutes', models.PositiveIntegerField(default=90, help_text='Default lesson duration in minutes')),
                ('default_payment_method', models.CharField(choices=[('payme', 'Payme'), ('cash', 'Cash')], default='payme', max_length=20)),
                ('enable_payme', models.BooleanField(default=True, help_text='Enable Payme payment integration')),
                ('enable_cash_payment', models.BooleanField(default=True, help_text='Enable cash payments')),
                ('enable_telegram_notifications', models.BooleanField(default=True, help_text='Enable Telegram notifications')),
                ('enable_sms_notifications', models.BooleanField(default=True, help_text='Enable SMS notifications')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('platform_name', models.CharField(default='TuranTalim ERP', help_text='Platform name', max_length=255)),
                ('support_email', models.EmailField(blank=True, help_text='Support email address', max_length=254)),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number', max_length=20)),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, help_text='Maintenance message displayed to users')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Who made the last update', max_length=255)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('payment_confirm', 'Confirm Payment')], max_length=50)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
