# Generated by Django 4.2.7 on 2025-12-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('document', 'Word Document'), ('audio', 'Audio File'), ('supplementary', 'Supplementary Material')], help_text='Type of resource', max_length=20)),
                ('title', models.CharField(help_text='Resource title (Turkish)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Resource description (Turkish)')),
                ('file', models.FileField(upload_to='lesson_resources/%Y/%m/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Audio duration in seconds', null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Whether resource is required for lesson')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Resource',
                'verbose_name_plural': 'Lesson Resources',
                'db_table': 'lesson_resources',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
